source 'https://rubygems.org'
ruby "1.9.3"


gem 'sass-rails', '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 1.3.0'
gem "haml-rails"


group :development do
  gem 'thin'
  gem 'meta_request', '0.2.0'
  gem 'guard'
  gem 'guard-livereload', require: false
  gem "rack-livereload"
  gem "github-pages"
end

gem 'rails', '4.2'
gem 'rails_12factor'
gem 'activeresource' # maybe activeresource is not needed
gem 'pg'
gem 'exception_notification'
gem 'pagedown-rails', '~> 1.1.3'
gem 'pg_search'
gem 'carrierwave'
gem 'acts-as-taggable-on', '~> 3.4'
gem "fog", "~> 1.27.0"
gem "rmagick", '2.13.2'
gem "tweet-button"
gem 'dalli'
gem 'newrelic_rpm'
gem "devise"
gem 'friendly_id'
gem "jquery-rails"
gem "differ"
gem 'bootstrap-sass'
gem "haml", ">= 3.0.0"
gem "rspec-rails", ">= 2.0.1", :group => [:development, :test]
gem 'neat'
gem 'execjs'
gem 'therubyracer'
gem "factory_girl_rails", "~> 4.5.0"
